# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            NPA OpenROV Blog
tagline:          A high school STEM program
url:              http://getpoole.com
paginate:         1
baseurl:          /

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/nparov
  - title: facebook
    url: https://www.facebook.com/NPAOpenROV

# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box 276
  - line: Arcata, CA 95518

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
